### ISSUE TITLE
Add batch support when pushing data to Salesforce

### ISSUE THREAD

**Issue by levelos** [thinkshout/salesforce#13]
Now that we have exposed all the SOAP api calls, we can implement a batching system in salesforce_push.

**Comment by levelos** [comment]
Currently still getting the following issue attempting to create SF objects using the SOAP API:

```
WD cron: SoapFault: common.exception.ApiQueryException: No such column '' on entity 'Contact'. If you are attempting to use a custom field, be sure to append  [error]
the '__c' after the custom field name. Please reference your WSDL or the describe call for the appropriate names. in SoapClient->__call() (line 499 of /profiles/ams_dev/libraries/salesforce/soapclient/SforceBaseClient.php).
```

**Comment by pcave** [comment]
What does the object looks like that you're sending to Salesforce. The documentation for using the partner API on this page http://wiki.developerforce.com/page/Getting_Started_with_the_Force.com_Toolkit_for_PHP is wrong. You don't create sObject instances. Instead they should be built like so:

$sObject = new stdClass();
$sObject->fields->FirstName  = 'Phillip';
$sObject->fields->LastName  =  'Cave';
$sObject->type = 'Contact';

...

create/upsert/whatever

**Comment by levelos** [comment]
Thanks @pcave, that's an interesting discrepancy ;) Got it to work using

``` php
$sobject = new stdClass();
$sobject->type = $mapping->salesforce_object_type;
foreach ($params as $key => $value) {
  $sobject->fields[$key] = $value;
}
```

**Comment by levelos** [comment]
Still some work to do, but this now works for creates, updates, and deletes.
