### ISSUE TITLE
de-dupe keys

### ISSUE THREAD

**Issue by levelos** [thinkshout/salesforce#21]
In addition to support for external entity keys, we may want to add more general de-duping support. These would be inclusive checkboxes on the field mappings. If no objects mappings are found, than an EFQ or SOQL query would be used to attempt to find a match before creating a new record.

**Comment by pcave** [comment]
FWIW, we definitely do upserts using the email field on the contact object. It's not obvious according to the docs, but indexed fields can also be used as a dedupe key. I don't think there is anything in a field describe that would tell you this though.

**Comment by levelos** [comment]
In the data we got back from object describe, the fields have an "externaId" flag, but only if explicitly set on custom fields. I tried using upsert with email and it failed, unfortunately. Would be excited if we could that to work!

**Comment by pcave** [comment]
Hm. Maybe they got a bit more restrictive in the REST API. Having to query before setting the action to create or update isn't ideal because you eat up another API call. Could use a non-standard email a field in Salesforce as a workaround, but that seems suboptimal, especially for existing orgs.
