### ISSUE TITLE
Fatal error when updating a user account.

### ISSUE THREAD

**Issue by pcave** [thinkshout/salesforce#22]
I mapped the user entity to a the contact object. When the user is updated I'm getting the following error on line 42:

Fatal error: Call to undefined method stdClass::entityType() in /var/www/ts.jacksonriverdev.com/public/sites/all/modules/salesforce/modules/salesforce_push/salesforce_push.module

**Comment by levelos** [comment]
Yeah, that could be due to me making too many assumptions about Entity API availability. FWIW, we've only so far tested with RedHen contacts. Should be easy to resolve regardless.
