### ISSUE TITLE
Handle multi-field fields (address)

### ISSUE THREAD

**Issue by tauno** [thinkshout/salesforce#26]
Need to be able to map to the components of multi-field fields in Drupal such as the address field.

**Comment by tauno** [comment]
Also text fields with input formatters - data is stored in _value, _format, and _summary fields. The rules data selector method of handling this is nice, but not sure how easy it would be to borrow.

**Comment by levelos** [comment]
Got a first pass at this committed @tauno and @bleeDev if you guys want to take a look.

**Comment by levelos** [comment]
Pending bugs, I think this one's covered.
