### ISSUE TITLE
Question about entity updates.

### ISSUE THREAD

**Issue by pcave** [thinkshout/salesforce#32]
I'm getting a fatal error when updating a user account entity. It's because the $wrapper->updated property does not exist. So I'm curious. Since the export is being done at entity save time, under what circumstances would the objects last sync time be greater then the last update time?

**Comment by pcave** [comment]
Would something like this be an acceptable fix for the missing updated property? The comments suggest we shouldn't assume it's there. This would always trigger an export regardless of last sync time.

$updated = property_exists($wrapper, 'updated') ? $wrapper->updated : NULL;

**Comment by levelos** [comment]
@pcave, we actually added an entityUpdated property which should be used here. Should be good in the attached commit. Salesforce Pull could cause that case to exist. @bleeDev, please confirm.
