### ISSUE TITLE
Implement fieldmap types on the salesforce side

### ISSUE THREAD

**Issue by tauno** [thinkshout/salesforce#37]
Could be handy to have fieldmap types on the salesforce side as well. Specifically thinking constants, but others might be useful as well.

/cc @levelos

**Comment by levelos** [comment]
I can see constants being useful. Any other ideas you had in mind?

**Comment by tauno** [comment]
The rules method you mentioned could be useful as well for people to be able to manipulate values from SF before they are pulled in. I could see other simple mapping types - concatenation, simple math, etc. Probably could be done in code cleaner.

May tie in to how we can create a new RH contact values for the redhen email field properties.
