### ISSUE TITLE
Converting date formats

### ISSUE THREAD

**Issue by tauno** [thinkshout/salesforce#38]
We started discussing this yesterday and I reverted some of the date handling code I put in place earlier this week before deciding I didn't catch the latest plan. Figured we should document how we think this will work.

Last I heard we were thinking that converting timestamp to the date/time salesforce wants should be done in glue code. 

For push, this could possibly be done using hook_salesforce_mapping_fieldmap_type_alter() to set our own value callback that converts timestamps to the salesforce format. 

On pull, we need to alter the value returned by salesforce into a timestamp. No hook to do this now. Maybe what #33 is intended to add.

/cc @bleeDev @levelos

**Comment by levelos** [comment]
I think making date handling part of core is a good approach, so lets explore how we can do that when you get in.

**Comment by tauno** [comment]
If drupal property is date and salesforce field type is date or datetime then convert between formats.

**Comment by pcave** [comment]
@levelos, you might run into conversion issues with booleans as well. PHP/Drupal have different variations on what constitutes a truth value. You might not run into it with entity integration, but we've encountered it integration other Drupal objects, mainly webform submission integration.

**Comment by tauno** [comment]
@pcave, thanks for the heads up. I'm seeing the boolean issue with another field - documented in #42
