### ISSUE TITLE
Move development to drupal.org

### ISSUE THREAD

**Issue by kostajh** [thinkshout/salesforce#49]
Now that an alpha is out and tagged on drupal.org (congratulations!), I think it would make sense to move development over to the d.o. issue queue. What do you all think?

**Comment by levelos** [comment]
Very reasonable suggestion @kostajh. As much as we prefer working in GitHub, there's lots of obvious benefits, namely in working with the community and gaining adoption, to working directly on d.o. We'd really need more control of the project on d.o., namely in managing the maintainers. If nothing else, we need to add our team members who are working on the project and ensure that we can still control the direction of 7.x-3.x branch. If that works, we can move development over, let me know.

**Comment by kostajh** [comment]
Ok, you've now got permissions to administer maintainers on d.o.

**Comment by levelos** [comment]
Thanks @kostajh, we'll work on transitioning development to d.o.
