### ISSUE TITLE
Any interest in creating some utility functions to get a list of mappable sobjects and recordtypes

### ISSUE THREAD

**Issue by pcave** [thinkshout/salesforce#53]
It would be nice to have some helper functions in the salesforce module. One that returns an array of mappable objects and another to return an array of record types when given an sobject name. We'll have to do this in several places for other, non-entity based integrations.

**Comment by levelos** [comment]
All Salesforce objects are already available via `Salesforce::objects()` and the record types are available in `Salesforce::objectDescribe($name)`. The latter could have a wrapper to just get the record types, but not sure how helpful that'd be.
