### ISSUE TITLE
Trigger activity message creation

### ISSUE THREAD

**Issue by tauno** [thinkshout/salesforce#68]
RedHen activity uses hook_entity_insert/update/delete to create messages. The current structure is that salesforce_activity_message_save generates the activity message and takes these arguments: mapping object, message type (push/pull, or maybe push, push_error, pull, pull_error), error code (optional), error message (optional). Those options might change a bit to handle HTTP status codes as well.

Some options for us:
1. Put the calls to salesforce_activity_message_save() in the salesforce_mapping/push/pull modules where the activity is generated and use module_exists/function_exists calls to make sure it's enabled.
2. Pass error/status info in with the mapping object when the mapping object is created or updated then use hook_entity_insert/update to call salesforce_activity_message_save().
3. Add a logging hook (hook_salesforce_activity?) that is invoked anytime we do a push or pull, then implement that hook in salesforce_activity.

3 is the most flexible, but is it too much of a performance hit when we might be syncing  thousands of objects?

Thoughts? @levelos @bleeDev

**Comment by levelos** [comment]
I don't believe adding a logging hook is any more expensive than implementing an existing one like `hook_salesforce_mappingobject_insert()`. At the end of the day, `salesforce_pull_process_records()` basically calls it's save method, so it seems that using the existing hooks and injecting the error data into the object make the most sense. E.g.,

``` php
     catch (Exception $e) {
        $message = $e->getMessage() . ' ' . t('Processing failed for entity %label associated with Salesforce Object ID: %sfobjectid',
            array(
              '%label' => $wrapper->label(),
              '%sfobjectid' => $sf_object['Id'],
            )
          );
        watchdog('Salesforce Pull', $message, array(), WATCHDOG_ERROR);
        salesforce_set_message('There were failures processing data from SalesForce. Please check the error logs.', 'error', FALSE);
  $mapping_object->error = $error_data;
      }
```

Maybe push is very different, I didn't look closely at it.

**Comment by bleeDev** [comment]
I think one reason to implement a hook would be if there is a use case for logging a message when not doing entity CRUD operations.

**Comment by tauno** [comment]
Went a different route - revisions!
