### ISSUE TITLE
Consider not not allowing drupal entity to be edited on mapping objects

### ISSUE THREAD

**Issue by tauno** [thinkshout/salesforce#71]
Currently, you can change both the drupal entity (type + Id) and SF object id of a mapping. This makes reasonable sense in terms of editing (find the mapping for SF object XYZ and set it to the correct Drupal entity AND find the mapping for Drupal entity 123 and set it to the correct SF object Id are both supported). It makes less sense when we start tracking activity history.

After @bleeDev and my conversation yesterday, I'm wondering if it would make more sense to only allow editing the Salesforce object Id. To change the Drupal entity on a mapping would require deleting the mapping (history is lost) and then recreating with the correct Drupal entity.

@levelos - I feel like we discussed this and decided to allow editing both, but I'm not recalling the reasoning. 

Thoughts?

**Comment by levelos** [comment]
What if you want to keep the history and the SF object but realize you're linked to the wrong drupal entity? Perhaps that's too fringe and not worth the potential hassle. It seems like a reasonable approach to take unless we can think of other issues.

**Comment by tauno** [comment]
That's the problem with the revision approach - you delete the mapping, you delete the history. Not sure if that's more or less confusing than having shared history when potentially the drupal entity and SF object have both changed.
