### ISSUE TITLE
saleforce_mapping_boolean_datatypefromsf.patch

### ISSUE THREAD

**Issue by mshaver** [thinkshout/salesforce#90]
saleforce_mapping_boolean_datatypefromsf.patch
The first part of the patch has been committed. The second part where we force pull values to boolean is not included. We currently cast to (int) which should be similar, but maybe not identical. Needs testing to see if this impacts this project.

**Comment by wxactly** [comment]
I gave this a test in 3.x, and as far as I can tell, this patch is not needed in order for checkbox/boolean values to sync properly between drupal and salesforce. It's possible this was fixed some other way in newer versions of the module. This would be a good one to test after upgrading to 3.x without the patch.
