### ISSUE TITLE
salesforce_mapping_admin_alphabetical-SF-fields.patch

### ISSUE THREAD

**Issue by mshaver** [thinkshout/salesforce#92]
salesforce_mapping_admin_alphabetical-SF-fields.patch
Add to module? We had this at one point but removed due to sometimes fields being grouped logically.

**Comment by wxactly** [comment]
@unclegcb fixed this in 3.x: a4a4a71

**Comment by wxactly** [comment]
Just updated that commit to use a different sort method, which handles lower case letters and numbers: 73e7234fcdc21bc635b755f6fffe5a641cd3d866
