### ISSUE TITLE
https://www.drupal.org/node/2611098#comment-10555542

### ISSUE THREAD

**Issue by mshaver** [thinkshout/salesforce#93]
Undefined variable patch.

**Comment by wxactly** [comment]
The patch wasn't quite right, but I did merge it in as-is: 1558efd, then I added a fix on top of that: 049cee3.

@tauno - do you mind taking a quick look and/or testing this one? Seems fairly straightforward

**Comment by tauno** [comment]
Looks good. Pushed to d.o for further review by community.
